export const PROFILES = [
  {
    id: "growth",
    name: "Growth",
    tagline: "High-Alpha Trend & Volatility Expansion",
    description: "Prioritizes rapid capital appreciation by targeting momentum breakouts and volatility expansions with dynamic risk management.",
    targetReturn: "+19% - +25% APY",
    riskTier: "High / Dynamic",
    badgeColor: "#3b82f6",
    recommendedAllocation: 7500,
    strategyIds: ["momentum", "volatility_sentinel"],
  },
  {
    id: "balanced",
    name: "Balanced",
    tagline: "Statistical Mean-Reversion & Rebound Alpha",
    description: "Balances steady growth with disciplined risk controls, buying high-probability statistical dips in proven market leaders.",
    targetReturn: "+14% - +18% APY",
    riskTier: "Moderate",
    badgeColor: "#10b981",
    recommendedAllocation: 5000,
    strategyIds: ["dip_buyer"],
  },
  {
    id: "conservative",
    name: "Conservative",
    tagline: "Capital Preservation & Disciplined DCA",
    description: "Focuses on steady compounding and drawdown defense through scheduled blue-chip accumulation and low-beta positioning.",
    targetReturn: "+9% - +13% APY",
    riskTier: "Low Risk",
    badgeColor: "#8b5cf6",
    recommendedAllocation: 3000,
    strategyIds: ["dca", "defensive_yield"],
  },
];

export const STRATEGIES = [
  {
    id: "dip_buyer",
    name: "Dip Buyer Alpha",
    profile: "balanced",
    tagline: "Oversold Bounce & Mean-Reversion",
    description: "Systematically detects intraday pullbacks in high-liquidity market leaders, accumulating at statistical support with strict risk parameters.",
    tone: "green",
    expectedReturn: "+14.8% APY",
    riskLevel: "Moderate Risk",
    winRate: "78%",
    allocationPreset: 5000,
    maxSpendPreset: 500,
    indicators: ["RSI < 38", "20-Day EMA Support", "Volume Divergence"],
    alphaVsSpy: "+5.4%",
    sharpeRatio: 2.35,
    maxDrawdown: "-4.8%",
  },
  {
    id: "momentum",
    name: "Momentum Breakout",
    profile: "growth",
    tagline: "High-Volume Trend Acceleration",
    description: "Captures rapid price expansions on high relative volume, joining established institutional trends with tight trailing stop protections.",
    tone: "blue",
    expectedReturn: "+22.4% APY",
    riskLevel: "Growth / Dynamic",
    winRate: "71%",
    allocationPreset: 7500,
    maxSpendPreset: 750,
    indicators: ["MACD Bullish Cross", "Relative Volume > 2.2x", "Resistance Breach"],
    alphaVsSpy: "+8.9%",
    sharpeRatio: 2.58,
    maxDrawdown: "-7.2%",
  },
  {
    id: "dca",
    name: "Value DCA Compounder",
    profile: "conservative",
    tagline: "Systematic Capital Accumulation",
    description: "Executes disciplined algorithmic dollar-cost averaging into top blue-chip leaders regardless of short-term volatility to optimize cost basis.",
    tone: "purple",
    expectedReturn: "+11.2% APY",
    riskLevel: "Conservative",
    winRate: "85%",
    allocationPreset: 3000,
    maxSpendPreset: 300,
    indicators: ["Scheduled Lot Sizing", "Valuation Floor", "Cash Reserve Guard"],
    alphaVsSpy: "+2.1%",
    sharpeRatio: 2.10,
    maxDrawdown: "-3.1%",
  },
  {
    id: "volatility_sentinel",
    name: "Volatility Sentinel",
    profile: "growth",
    tagline: "Bollinger Squeeze & Expansion",
    description: "Identifies volatility contractions followed by aggressive directional expansion to enter trades at early stage volatility spikes.",
    tone: "amber",
    expectedReturn: "+19.5% APY",
    riskLevel: "Aggressive",
    winRate: "74%",
    allocationPreset: 5000,
    maxSpendPreset: 600,
    indicators: ["Bollinger Band Squeeze", "ATR Breakout", "Implied Vol Delta"],
    alphaVsSpy: "+6.8%",
    sharpeRatio: 2.22,
    maxDrawdown: "-6.5%",
  },
  {
    id: "defensive_yield",
    name: "Defensive Yield Shield",
    profile: "conservative",
    tagline: "Low-Beta Capital Preservation",
    description: "Prioritizes capital defense and low drawdown by allocating to low-beta index components and resilient defensive mega-caps.",
    tone: "slate",
    expectedReturn: "+9.6% APY",
    riskLevel: "Ultra Low Risk",
    winRate: "89%",
    allocationPreset: 4000,
    maxSpendPreset: 400,
    indicators: ["Beta < 0.75", "Maximum 4% Drawdown", "High Cash Drag"],
    alphaVsSpy: "+1.2%",
    sharpeRatio: 2.45,
    maxDrawdown: "-2.4%",
  },
];
